language: node_js
node_js:
  - "6.13.0"
cache:
  directories:
    - "node_modules"
env:
  - DB_HOST=localhost DB_USER=postgres DB_PW=
services:
  - postgresql
before_script:
  - psql -c 'create database products_test;' -U postgres
  - psql -c 'create database products;' -U postgres
  - knex migrate:latest --env development
  - knex migrate:latest --env test
  - npm run dev-db:seed
  - npm run test-db:seed