FROM node:8-alpine
ADD https://github.com/ufoscout/docker-compose-wait/releases/download/2.2.1/wait /wait
RUN chmod +x /wait
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app
COPY . .
RUN npm install
ENV NODE_ENV prod
ARG port=8002
EXPOSE $port
CMD /wait && node server/index.js