# docker-compose.yml
version: "3"
services:
  app:
    build:
      context: ../
      dockerfile: docker/Dockerfile.node
      args:
        port: 8002
    depends_on:
      - db
    ports:
      - "8002:8002"
    environment:
      NODE_ENV: production
      DB_HOST: db
      DB_PASSWORD: postgres
      DB_USER: postgres
      DB_NAME: products
  db:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      NODE_ENV: production
      DB_HOST: db
      DB_PASSWORD: postgres
      DB_USER: postgres
      DB_NAME: products
volumes:
  pgdata:
