module.exports.data = {
  shoeLink1: [
    'https://s3.us-east-2.amazonaws.com/sdc-images-smaller/image+(1).webp',
    'https://s3.us-east-2.amazonaws.com/sdc-images-smaller/image+(2).webp',
    'https://s3.us-east-2.amazonaws.com/sdc-images-smaller/image+(3).webp',
    'https://s3.us-east-2.amazonaws.com/sdc-images-smaller/image+(4).webp',
    'https://s3.us-east-2.amazonaws.com/sdc-images-smaller/image+(5).webp',
  ],
  shoeLink2: [
    'https://s3.us-east-2.amazonaws.com/sdc-images-smaller/image+(6).webp',
    'https://s3.us-east-2.amazonaws.com/sdc-images-smaller/image+(7).webp',
    'https://s3.us-east-2.amazonaws.com/sdc-images-smaller/image+(8).webp',
    'https://s3.us-east-2.amazonaws.com/sdc-images-smaller/image+(9).webp',
    'https://s3.us-east-2.amazonaws.com/sdc-images-smaller/image+(10).webp',
  ],
  shoeLink3: [
    'https://s3.us-east-2.amazonaws.com/sdc-images-smaller/image+(11).webp',
    'https://s3.us-east-2.amazonaws.com/sdc-images-smaller/image+(12).webp',
    'https://s3.us-east-2.amazonaws.com/sdc-images-smaller/image+(13).webp',
    'https://s3.us-east-2.amazonaws.com/sdc-images-smaller/image+(14).webp',
    'https://s3.us-east-2.amazonaws.com/sdc-images-smaller/image+(15).webp',
  ],
  shoeLink4: [
    'https://s3.us-east-2.amazonaws.com/sdc-images-smaller/image+(16).webp',
    'https://s3.us-east-2.amazonaws.com/sdc-images-smaller/image+(17).webp',
    'https://s3.us-east-2.amazonaws.com/sdc-images-smaller/image+(18).webp',
    'https://s3.us-east-2.amazonaws.com/sdc-images-smaller/image+(19).webp',
    'https://s3.us-east-2.amazonaws.com/sdc-images-smaller/image+(20).webp',
  ],
  shoeLink5: [
    'https://s3.us-east-2.amazonaws.com/sdc-images-smaller/image+(21).webp',
    'https://s3.us-east-2.amazonaws.com/sdc-images-smaller/image+(22).webp',
    'https://s3.us-east-2.amazonaws.com/sdc-images-smaller/image+(23).webp',
    'https://s3.us-east-2.amazonaws.com/sdc-images-smaller/image+(24).webp',
    'https://s3.us-east-2.amazonaws.com/sdc-images-smaller/image+(25).webp',
  ],
  shoeLink6: [
    'https://s3.us-east-2.amazonaws.com/sdc-images-smaller/image+(26).webp',
    'https://s3.us-east-2.amazonaws.com/sdc-images-smaller/image+(27).webp',
    'https://s3.us-east-2.amazonaws.com/sdc-images-smaller/image+(28).webp',
    'https://s3.us-east-2.amazonaws.com/sdc-images-smaller/image+(29).webp',
    'https://s3.us-east-2.amazonaws.com/sdc-images-smaller/image+(30).webp',
  ],
  shoeLink7: [
    'https://s3.us-east-2.amazonaws.com/sdc-images-smaller/image+(31).webp',
    'https://s3.us-east-2.amazonaws.com/sdc-images-smaller/image+(32).webp',
    'https://s3.us-east-2.amazonaws.com/sdc-images-smaller/image+(33).webp',
    'https://s3.us-east-2.amazonaws.com/sdc-images-smaller/image+(34).webp',
    'https://s3.us-east-2.amazonaws.com/sdc-images-smaller/image+(35).webp',
  ],
  shoeLink8: [
    'https://s3.us-east-2.amazonaws.com/sdc-images-smaller/image+(36).webp',
    'https://s3.us-east-2.amazonaws.com/sdc-images-smaller/image+(31).webp',
    'https://s3.us-east-2.amazonaws.com/sdc-images-smaller/image+(30).webp',
    'https://s3.us-east-2.amazonaws.com/sdc-images-smaller/image+(29).webp',
    'https://s3.us-east-2.amazonaws.com/sdc-images-smaller/image+(28).webp',
  ],
  product1: {
    colors: 'Grey, Grey, Grey',
    type: "Men's Running",
    model: "UltraBoost All Terrain Shoes",
    sizes: "6, 6.5, 7, 8, 8.5, 10, 14, 14.5, 16",
    price: 180.00,
    image_id: 1,
    review_count: 1200,
    avg_stars: 4.75
  },
  product2: {
    color: 'Night Red, Noble Maroon, Bright Blue',
    type: "Men's Running",
    model: "UltraBoost All Terrain Shoes",
    sizes: "6, 6.5, 7, 8, 8.5, 9, 9.5, 10, 14, 14.5",
    price: 180.00,
    image_id: 2,
    avg_stars: 4.1,
    review_count: 320
  },
  product3: {
    color: 'Chalk White, Cloud White, Grey',
    type: "Men's Running",
    model: "UltraBoost All Terrain Shoes",
    sizes: "6, 6.5, 7, 8, 8.5, 9, 9.5",
    price: 180.00,
    image_id: 3,
    avg_stars: 4.7,
    review_count: 150
  },
};
